version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "2050:80"  # Map port 3000 on the host to port 80 in the container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    restart: unless-stopped