version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun_frontend
    ports:
      - "2050:80"  # Map port 2050 on the host to port 80 in the container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bun_backend
    ports:
      - "2051:8080"  # Example port mapping for backend service
    environment:
      - REMOTE_DB=mongodb://100.74.72.97:27017/Bun-Torrent?directConnection=true
      - NODE_ENV=production
      - HTTP_PROXY=http://torproxy:8118  # Set HTTP proxy for backend service
      - HTTPS_PROXY=http://torproxy:8118  # Set HTTPS proxy for backend service
      # Add more environment variables as needed
    depends_on:
      - torproxy
    restart: unless-stopped

  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    ports:
      - "8118:8118"
      - "9050:9050"
    restart: unless-stopped

networks:
  default:
    name: bun_network
